### ISSUE TITLE
Filtering before matching

### ISSUE THREAD

**Issue by ahuds001** [ppact/processing#1]
There should be functionality where, prior to attempting to match officers between police departments we first check whether a match is possible. The logic is as follows:
- A match between departments is only possible if an officer has transferred
- If an officer has transferred then their first known date in the new department has to be greater than the last known date in the prior department 

The work will be as follows:
1. From the events data generate an officer dataset that has the first and last known interactions in their departments
2. Write a function that, given an officer and their agency start date, returns a subset of candidates in the master dataset whose last known date is less than the officer start date in the new agency

Is this right @pckhoi? Am I missing anything from our conversation?

**Comment by pckhoi** [comment]
Yes, I think that is essentially what we should try to do. However I think how we go about it will affect the matching speed substantially. Have you heard of indexing or blocking in data matching? Essentially we try to assign each individual officer into one or multiple buckets such that we only need to compare officers within a bucket. In this way we avoid quadratic time when matching. One index that I frequently use to great effect is the first character of officer name. Each index is very simple, just an iterator that return pairs of records that need to be matched (you can look at `NoopIndex` and `ColumnsIndex`). In this case we probably want to use an additional date index of some sort.

I think basically each officer has a date range (or multiple date ranges) where they possibly worked at another agency. So we should try to turn the date range into an index. One obvious technique that came to my mind is to discretize the date range, split them into multiple chunks - one month each. E.g. if an officer quit an agency in March 2015 and we want to compare until December 2020, we slot him into `9 + 12 * (2020 - 2016)` buckets.

So here's the things we'll probably want to make:
- Create a `DateRangeIndex` class which discretize a date range into monthly values.
- Create a `MultiIndex` class which allow combination of multiple indexes. In this case it would be nice to be able to write `MultiIndex([ColumnsIndex(['firsrt_char']), DateRangeIndex('available_date')])`
- Make it so that `ThresholdMatcher` ignore pairs that it has already seen before as I anticipate for there to be lots of pairs that will belong to multiple buckets.

Let me know what you think.

**Comment by pckhoi** [comment]
I started using the matching package in other projects so I just split it to separate [repo](https://github.com/pckhoi/datamatch) and published to PyPi under the name `datamatch`. Let's contribute directly there.

**Comment by ahuds001** [comment]
Sounds good, closing this issue to move it over to https://github.com/pckhoi/datamatch
