### ISSUE TITLE
Ponchatoula PD CPRR 2010-2020

### ISSUE THREAD

**Issue by pckhoi** [ppact/processing#68]

**Comment by pckhoi** [comment]
@ayyubibrahimi I want to ask about the main purpose of standardizing complaint related columns like `allegation`, `disposition` and `action`. What do we want to achieve here?

I ask because I run into some values for `allegation` that are quite similar but I don't know if I should group them as one thing:
- discourtesy
- discourteous to co-workers
- improper comments to city hall employees
- offensive language

There are many cases like this where what to do is ambiguous because the desired outcome isn't clear.

**Comment by ayyubibrahimi** [comment]
This was on my mind recently as well as I thought about references. I'm not sure that we can achieve anything because of the ambiguity and variation in data by agency therefore I'm inclined to think that the look_up table is best used to produce a clean output and to prevent missed typos. What are you thinking?

**Comment by pckhoi** [comment]
I want to err toward investing less time into vague goals. Should there be a need for higher quality output we can always go back and improve it. For now though if it's highly free flow text I'm not even going to use lookup table if there are just some typos here and there.
